---
version: "3.8"
services:
  derod:
    build: .
    hostname: derod
    restart: unless-stopped
    volumes:
      - ./mainnet:/mainnet
      - ./pool.db:/pool.db
    ports:
      - 10.200.10.200:20209:20209
    networks:
      default:
    command: /dero-wallet --wallet-file=pool.db --unlocked --daemon-address=10.200.10.200:40402 --rpc-server --rpc-bind=10.200.10.200:20209